# Generated by Django 4.0.6 on 2022-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dishname',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
